language: java
jdk:
  - openjdk8


branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'


script:
  - "./gradlew clean build"


before_deploy:
  - mkdir -p deploy
  - cp build/libs/*.jar deploy/application.jar
  - cp Procfile deploy/Procfile
  - cd deploy && zip -r deploy.zip .

deploy:
  provider: elasticbeanstalk
  zip_file: deploy.zip
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-2"
  app: "restaurant"
  env: "Restaurant-env"
  bucket_name: "elasticbeanstalk-us-east-2-572207109054"  # S3 bucket name
  on:
    branch: master